### ISSUE TITLE
Does not work with other color schemes

### ISSUE THREAD

**Issue by katawful** [psliwka/termcolors.nvim#1]
When running this with [both](https://github.com/katawful/kat.vim) of [my](https://github.com/katawful/kat.nvim) termguicolors colorschemes, the output fails like so:

```
E5108: Error executing lua ...ite/pack/packer/start/termcolors.nvim/lua/termcolors.lua:85: bad argument #
1 to 'lower' (string expected, got nil)                                                                  
stack traceback:                                                                                         
        [C]: in function 'lower'                                                                         
        ...ite/pack/packer/start/termcolors.nvim/lua/termcolors.lua:85: in function 'generate_kitty_confi
g'                                                                                                       
        ...ite/pack/packer/start/termcolors.nvim/lua/termcolors.lua:93: in function 'show'               
        [string ":lua"]:1: in main chunk  
```

**Comment by psliwka** [comment]
Thanks for reporting this, @katawful! I just pushed a fix which will hopefully prevent the plugin from crashing on these colorschemes. Unfortunately, this fix does not address the underlying issue, i.e. the fact that some of colors could not be scraped correctly. Feel free to raise another issue if you encounter any missing colors in rendered Kitty config.
